### PR TITLE
EOS-25931: Community build: Steps to generate cortx-all docker image. 

### PR DESCRIPTION
**Pull request by shailesh-vaidya**
### Describe your changes in brief 
CORTX is supported on K8s environment now. This PR adds scripts and instructions to build cortx-all image for community developers. This will enable developers to test code CORTX code changes in the K8s enviornment. 

### Changes
 - [ ] Why is this change required? What problem does it solve?
        This PR will enable developers to test code CORTX code changes in the K8s environment. 
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
        @nikhilpatil2995 Tested on the local environment.  
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Checklist
 - [x] tested locally
 - [ ] added new dependencies
 - [x] updated the docs
 - [ ] added a test

-----
[View rendered doc/community-build/docker/cortx-all/README.md](https://github.com/shailesh-vaidya/cortx/blob/cortx-all-image/doc/community-build/docker/cortx-all/README.md)

### CODE REVIEW

**Review by gauravchaudhari02 — APPROVED** [review]

**Comment by gauravchaudhari02** [comment]
@shailesh-vaidya , Can't we put scripts in `script` folder rather than `doc` folder

**Comment by nikhilpatil2995** [comment]
@shailesh-vaidya , Tested this on outside seagate network in AWS ec2 instance and cortx-all image got build successfully. 

[root@ip-172-31-46-79 cortx-all]# docker run --rm 7c7b2da38304 cat /opt/seagate/cortx/RELEASE.INFO
---
NAME: "CORTX"
OS: "CentOS Linux release 7.9.2009 (Core)"
DATETIME: "22-Nov-2021 12:31 UTC"
COMPONENTS:
    - "cortx-py-utils-2.0.0-0_0457ceb.noarch.rpm"
    - "cortx-hare-2.0.0-0_gitc0eb48a.el7.x86_64.rpm"
    - "cortx-motr-2.0.0-0_gitad1f2b09_3.10.0_1160.el7.x86_64.rpm"
    - "cortx-s3server-2.0.0-0_gita92413d5_el7.x86_64.rpm"
    - "cortx-csm_agent-2.0.0-0_b3c80e82.x86_64.rpm"
    - "cortx-provisioner-2.0.0-0_ac9bb329.noarch.rpm"
THIRD_PARTY_RPM_PACKAGES:
    - "crontabs-1.11-6.20121102git.el7.noarch.rpm"
    - "haproxy22-2.2.9-3.el7.ius.x86_64.rpm"
    - "java-1.8.0-openjdk-headless-1.8.0.262.b10-1.el7.x86_64.rpm"
    - "jq-1.6-2.el7.x86_64.rpm"
    - "kafka-2.13_2.7.0-el7.x86_64.rpm"
    - "logrotate-3.8.6-19.el7.x86_64.rpm"
    - "python3-3.6.8-17.el7.x86_64.rpm"
    - "python36-dbus-1.2.4-4.el7.x86_64.rpm"
    - "python36-m2crypto-0.35.2-5.el7.x86_64.rpm"
    - "python36-psutil-5.6.7-1.el7.x86_64.rpm"
    - "sshpass-1.06-2.el7.x86_64.rpm"
    - "sudo-1.8.23-10.el7.x86_64.rpm"
    - "symas-openldap-clients-2.4.58-1.el7.x86_64.rpm"
    - "which-2.20-7.el7.x86_64.rpm"
THIRD_PARTY_PYTHON_PACKAGES:
    - aiohttp==3.6.1
    - argcomplete==1.12.3
    - async-timeout==3.0.1
    - attrs==20.3.0
    - bcrypt==3.2.0
    - boto3==1.10.27
    - botocore==1.13.50
    - certifi==2020.12.5
    - cffi==1.14.5
    - chardet==3.0.4
    - click==7.1.2
    - configparser==4.0.2
    - confluent-kafka==1.5.0
    - cortx-provisioner==2.0.0
    - cortx-py-utils==2.0.0
    - cryptography==2.8
    - cycler==0.10.0
    - dataclasses==0.7
    - decorator==4.4.2
    - dict2xml==1.6.1
    - docutils==0.16
    - elasticsearch==7.12.0
    - elasticsearch-dsl==7.3.0
    - Flask==1.1.1
    - idna==2.10
    - idna-ssl==1.1.0
    - importlib-metadata==4.8.2
    - itsdangerous==1.1.0
    - Jinja2==2.11.1
    - jmespath==0.10.0
    - jsonschema==3.2.0
    - kiwisolver==1.2.0
    - lockfile==0.12.2
    - M2Crypto==0.35.2
    - MarkupSafe==1.1.1
    - marshmallow==3.2.1
    - matplotlib==3.1.3
    - multidict==4.7.6
    - netifaces==0.10.9
    - networkx==2.4
    - numpy==1.19.2
    - paramiko==2.7.1
    - pathlib==1.0.1
    - pika==1.1.0
    - ply==3.9
    - prettytable==0.7.2
    - psutil==5.6.7
    - pyasn1==0.4.7
    - pyasn1-modules==0.2.7
    - pycparser==2.20
    - pyinotify==0.9.6
    - PyNaCl==1.4.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-consul==1.1.0
    - python-crontab==2.5.1
    - python-daemon==2.2.4
    - python-dateutil==2.8.1
    - python-ldap==3.1.0
    - PyYAML==5.1.2
    - requests==2.25.1
    - s3backgrounddelete==2.0.0
    - s3cipher==2.0.0
    - s3confstore==2.0.0
    - s3msgbus==2.0.0
    - s3transfer==0.2.1
    - schematics==2.1.0
    - secure==0.2.1
    - six==1.16.0
    - statsd==3.2.2
    - toml==0.10.0
    - typing-extensions==4.0.0
    - urllib3==1.26.4
    - Werkzeug==1.0.1
    - xmltodict==0.12.0
    - yarl==1.6.0
    - yq==2.12.2
    - zipp==3.6.0
    - zope.component==4.6.2
    - zope.deferredimport==4.3.1
    - zope.deprecation==4.4.0
    - zope.event==4.5.0
    - zope.hookable==5.0.1
    - zope.interface==5.2.0
    - zope.proxy==4.3.5

**Comment by shailesh-vaidya** [comment]
> @shailesh-vaidya , Can't we put scripts in `script` folder rather than `doc` folder

@gauravchaudhari02  I could not find the script folder in the repo. Could you point me to the `script`  folder.  I agree we need to re-arrange the folder structure here. Maybe we can take it as an improvement.

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Review by nikhilpatil2995 — APPROVED** [review]

**Pull request merged**
