### PR TITLE
Update QSG link to point to the new default branch in cortx-k8s

### LINKED ISSUE #1381: Need AWS Cloud Formation template
We now have K8S deployment guide for AWS which works great but has a lot of manual steps. It would be awesome if it was improved with a Cloud Formation template.
https://github.com/Seagate/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md

FYI @gregnsk

### PR DESCRIPTION
**Pull request by trshaffer**
The cortx-k8s repo changed their default branch to `integration`, so new updates will show up there. The updated QSG linked here uses CloudFormation, so this will also resolve #1381 

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

-----
[View rendered QUICK_START.md](https://github.com/trshaffer/cortx/blob/update-k8s-branch/QUICK_START.md)

### CODE REVIEW

**Comment by osowski** [comment]
Things should still reference `main` as the initial landing spot for items that are "released", as that is the branch our releases are based off of. The `integration` branch is a true integration branch and not one we would be linking to from external repositories or entry points.

@walterlopatka , correct me if you think otherwise, but I think we want to keep the reference here pointing to `main` and not `integration` ?

**Comment by walterlopatka** [comment]
I agree with @osowski here.  Integration is where changes are happening.  Main is the stable branch where I expect most contributors to follow.

**Comment by trshaffer** [comment]
@walterlopatka then would you suggest waiting to update this link until the new QSG makes its way to `main`?

**Comment by walterlopatka** [comment]
@trshaffer I'm not sure I understand.  I think the QSG should always refer to main, not integration, when instructing people to download/run CORTX because main will be stable while integration is work in progress.

**Comment by trshaffer** [comment]
Whoops @walterlopatka, I typed that out too fast. I'm trying to get  #1381 closed (put CloudFormation instructions on the main quick start page). Looks like the updated guide made it to `main` already, so this PR is unnecessary

**Pull request closed without merging**
