### PR TITLE
Matt main

### PR DESCRIPTION
**Pull request by hessio**
Removing secret and access keys from CORTX-Flask-MediaViewer integration

Signed-off-by: hessio <patrick.hession@seagate.com>

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

-----
[View rendered doc/integrations/CORTX-Flask-MediaViewer/README.md](https://github.com/Seagate/cortx/blob/matt-main/doc/integrations/CORTX-Flask-MediaViewer/README.md)

### CODE REVIEW

**Comment by mukul-seagate11** [comment]
@hessio, can you fix the Codacy issues & signed-off your commits as DCO is failing

**Review by mukul-seagate11 — CHANGES_REQUESTED** [review]
fix Codacy issues & signed-off your commits as DCO is failing

**Comment by mukul-seagate11** [comment]
> fix Codacy issues & signed-off your commits as DCO is failing

@hessio, Codacy check is still failing

**Comment by mukul-seagate11** [comment]
@hessio, it has conflicts so please fix

**Comment by hessio** [comment]
> @hessio, it has conflicts so please fix

Conflicts are resolved, the Codacy issues are bugs please check Codacy rules as they are bugs in Codacy

**Comment by mukul-seagate11** [comment]
> Thank you for your pull request and welcome to our community. We could not parse the GitHub identity of the following contributors: **root**. This is most likely caused by a git client misconfiguration; please make sure to:
> 
> 1. check if your git client is configured with an email to sign commits `git config --list | grep email`
> 2. If not, set it up using `git config --global user.email email@example.com`
> 3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

@hessio, look like you haven't configured your git config username & email on your local server

**Comment by hessio** [comment]
Duplicate

**Pull request closed without merging**
