### PR TITLE
Update ProvisionReleaseBuild.md

### PR DESCRIPTION
**Pull request by justinzw**
A reboot is needed in order to disable SELinux. 

Signed-off-by: Justin Woo <justin.woo@seagate.com>

-----
[View rendered doc/ProvisionReleaseBuild.md](https://github.com/Seagate/cortx/blob/justinzw-patch-4/doc/ProvisionReleaseBuild.md)

### CODE REVIEW

**Comment by justinzw** [comment]
> Sorry Justin would be able to remove the reboot that occurs after changing the hostname, so that the user will only have to reboot once they have disabled selinux and changed the hostname instead of being told to do this twice?

@hessio thanks for the suggestion. I removed the reboot and also made some minor edits so it's easier to copy and paste.

**Review by hessio — APPROVED** [review]
Nice, looks good thanks @justinzw

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by mukul-seagate11** [comment]
@justinzw , update your branch so the PR can be merged

**Pull request merged**
