### PR TITLE
Add Instructions for Oracle VM VirtualBox users

### PR DESCRIPTION
**Pull request by harrison-seow-seagate**
Regarding to [Issue 539](https://github.com/Seagate/cortx/issues/539).
6 Jan, 2021: Instructions tested using OVA release 1.0.2 on Windows 10 Desktop running Oracle VM VirtualBox 6.1.

### CODE REVIEW

**Comment by mukul-seagate11** [comment]
@harrison-seow-seagate, please make sure you configure your email to sign commits as per below commands,

$ git config --list | grep email
$ git config --global user.email email@example.com

**Comment by harrison-seow-seagate** [comment]
@mukul-seagate11 Had trouble signing off the commit after merge so I reset back to my initial commit...

**Comment by mukul-seagate11** [comment]
> @mukul-seagate11 Had trouble signing off the commit after merge so I reset back to my initial commit...

I see all commits are signed but actually you have to make a practivce for committing a code via,

$ git commit -s -m 'This is my commit message'

**Review by johnbent — APPROVED** [review]
Great stuff @harrison-seow-seagate !

**Comment by harrison-seow-seagate** [comment]
Is there something blocking this pull request?

**Comment by mukul-seagate11** [comment]
@justinzw, do you want to add/review anything before we merge the PR?

**Comment by johnbent** [comment]
Sorry for delay!  We missed this one!  We should have merged it a long time ago.  Thanks for your awesome contribution!

**Pull request merged**
