### PR TITLE
[CORTX 2022 Hackathon] - Add CORTX Terraform Provider Integration

### PR DESCRIPTION
**Pull request by DMW2151**
add cortx-terraform readme - see comments in readme

### Describe your changes in brief

Adds readme for CORTX terraform provider integration

### Changes
 - [x] Why is this change required? - What problem does it solve? - Hackathon feature. Builds a integration between the CORTX API and Hashicorp [Terraform](https://www.terraform.io/). Infrastructure As Code tools like Terraform can allow organizations to standardize infrastructure and policies across multiple regions, environments, applications, etc. With the this provider, users can now include CORTX resources with their other infrastructure deployments rather than relying on custom scripts or one-off deployment patterns. 

 - [x] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [x] Please describe in detail how you tested your changes. - Tested on AWS C5.large instance (v1.04) following guide from [CORTX EC2 Setup Guide](https://github.com/Seagate/cortx/blob/main/doc/integrations/AWS_EC2/README.md) and on a one-off Cloudshare instance (v2.0.0-790).

 - [x] Include details of your testing environment, and the tests you ran to - N.A - external to MOTR or CORTX functionality, just adds provider functionality. Build depends on Terraform > v1.0.3 and Go > v1.16.

 - [x] How your change affects other areas of the code, etc.

### Screenshots (if appropriate)

- Refer to video description in readme.md

### Checklist
 - [x] tested locally
 - [x] added new dependencies
 - [x] updated the docs
 - [x] added a test

-----
[View rendered readme.md](https://github.com/DMW2151/cortx/blob/main/readme.md)

### CODE REVIEW

**Comment by mukul-seagate11** [comment]
> Thanks for your contribution! The CLA bot has flagged your contribution as not having a Contributor License Agreement in place. Note that this is not needed in the overwhelming majority of instances and this warning will usually be ignored. The code reviewers will make a determination and may ask you to sign a CLA or may choose to ignore this warning. More information about this can be found [here](https://github.com/Seagate/cortx/blob/master/doc/dco_cla.md).

@DMW2151, I see you haven't signed the CLA agreement so can sign the same so that we can review & merge the PR
CC @johnbent

**Comment by mukul-seagate11** [comment]
> > Thanks for your contribution! The CLA bot has flagged your contribution as not having a Contributor License Agreement in place. Note that this is not needed in the overwhelming majority of instances and this warning will usually be ignored. The code reviewers will make a determination and may ask you to sign a CLA or may choose to ignore this warning. More information about this can be found [here](https://github.com/Seagate/cortx/blob/master/doc/dco_cla.md).
> 
> @DMW2151, I see you haven't signed the CLA agreement so can sign the same so that we can review & merge the PR and also your commits are not signed-off so DCO is failing.
CC @johnbent

**Comment by johnbent** [comment]
Thanks @mukul-seagate11 . Although, we have determined that CLA is not needed for hackathon. 

However, @DMW2151, if you know how to add DCO, that would be nice! :)

**Comment by DMW2151** [comment]
Apologies for letting this go stale, are there docs I can reference to add the DCO?

**Comment by mukul-seagate11** [comment]
@DMW2151, yes please modify your commit & update your local branch as DCO is now auto sign off through GitHub's web Interface

**Comment by hessio** [comment]
Why was this closed?

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by mukul-seagate11** [comment]
> @DMW2151, yes please modify your commit & update your local branch as DCO is now auto sign off through GitHub's web Interface

@DMW2151, you can refer,https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/ for signing your commits

**Pull request merged**
