### PR TITLE
Added a note in VirtualBox steps

### LINKED ISSUE #985: Virtual Box VMs may not have network devices setup right
The `For Oracle VM VirtualBox Users Only' section in [VM setup documentation](https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst#cortx-on-open-virtual-appliance) is sometimes not reproducible.

1. Network devices can have different names(enp0s8, enp0s9, enp0s17 instead of  enp0s3, enp0s8, enp0s9)See [here](https://youtu.be/-JPrpL1_8Mg?t=801)
2. Restarting VM sometimes switches the IPs of network devices. See initially [here](https://youtu.be/-JPrpL1_8Mg?t=801) and after restart [here](https://youtu.be/-JPrpL1_8Mg?t=2153)

Tested on:
MacOS: 10.15.5
Oracle VirtualBox: Version 6.0.4 r128413 (Qt5.6.3)
Cortx image: cortx-va-1.0.3.va

### PR DESCRIPTION
**Pull request by hessio**
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>

Resolves #985 

### Changes
 - Added a note to address concerns in [issue #985](https://github.com/Seagate/cortx/issues/985)

### How Has This Been Tested? (Optional)
 - MacOS: 10.15.5
- Oracle VirtualBox: Version 6.0.4 r128413 (Qt5.6.3)
- Cortx image: cortx-va-1.0.3.ova

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by mukul-seagate11** [comment]
please update your branch so that the changes get merged

**Comment by hessio** [comment]
Updated. @mukul-seagate11

**Comment by mukul-seagate11** [comment]
still I see the branch is not updated

**Comment by hessio** [comment]
Ok updated again.

**Pull request merged**
