### PR TITLE
Signed-off-by: Mayur Gupta <Mayur.Gupta@Seagate.com>

### PR DESCRIPTION
**Pull request by TechWriter-Mayur**
Added Newsletter links as per issue #657 

-----
[View rendered Community_Roadmap.md](https://github.com/TechWriter-Mayur/cortx/blob/main/Community_Roadmap.md)

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by johnbent** [comment]
Please change 'LINK' to 'PDF' for links to pdf files.  Also, please remove the checkmarks for the first two newsletters since we don't have them.

**Review by johnbent — CHANGES_REQUESTED** [review]
Please change 'LINK' to 'PDF' for pdf links and remove the checkmarks for the 2 first newsletters for which we don't have the PDFs.

**Comment by johnbent** [comment]
Hey Mayur,

This PR is good but the title of it should be descriptive of the PR.  Right now, you have put your DCO into the title of the PR.  That should go in the body of the PR and the title should be something like, "Improving links in community roadmap."

**Pull request merged**
