### PR TITLE
Updated CentOS version

### PR DESCRIPTION
**Pull request by Saumya-Sunder**
Updated CentOS version from 7.7 to 7.8 and ISO link

Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>

### CODE REVIEW

**Comment by shailesh-vaidya** [comment]
We can use https://vault.centos.org/7.8.2003/isos/x86_64/CentOS-7-x86_64-DVD-2003.iso as more generic URL. 

On side note CentOS 7.8.2003 is deprecated. It will not no longer get any updates or security fix's. We can continue use it just OS packages will be from [vault](https://vault.centos.org/) repo.  Please refer http://mirror.centos.org/centos-7/7.8.2003/readme 

CentOS has moved to http://mirror.centos.org/centos-7/7.9.2009/ with [kernel-3.10.0-1160.el7.x86_64.rpm](http://mirror.centos.org/centos-7/7.9.2009/os/x86_64/Packages/kernel-3.10.0-1160.el7.x86_64.rpm)

**Comment by Saumya-Sunder** [comment]
Thanks @shailesh-vaidya I will update it :)

**Comment by johnbent** [comment]
Yes, @Saumya-Sunder , please make the change requested by @shailesh-vaidya .

**Review by johnbent — CHANGES_REQUESTED** [review]
Yes, @Saumya-Sunder , please make the change requested by @shailesh-vaidya .

**Comment by Saumya-Sunder** [comment]
> We can use https://vault.centos.org/7.8.2003/isos/x86_64/CentOS-7-x86_64-DVD-2003.iso as more generic URL.
> 
> On side note CentOS 7.8.2003 is deprecated. It will not no longer get any updates or security fix's. We can continue use it just OS packages will be from [vault](https://vault.centos.org/) repo. Please refer http://mirror.centos.org/centos-7/7.8.2003/readme
> 
> CentOS has moved to http://mirror.centos.org/centos-7/7.9.2009/ with [kernel-3.10.0-1160.el7.x86_64.rpm](http://mirror.centos.org/centos-7/7.9.2009/os/x86_64/Packages/kernel-3.10.0-1160.el7.x86_64.rpm)

done @shailesh-vaidya and @johnbent, please check and approve.

**Comment by johnbent** [comment]
@Saumya-Sunder , please follow the Hua request above.

**Pull request merged**
