### PR TITLE
Added Terraform scripts to setup AWS instance for CORTX deployment.

### PR DESCRIPTION
**Pull request by shailesh-vaidya**
### Changes
 - [x] Why is this change required? What problem does it solve?
        Added terraform scripts to set up AWS instances which can be used to deploy CORTX. This will help community developers 
        to test CORTX quickly. 
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [x] Please describe in detail how you tested your changes.
       Validated on AWS infrastructure. 
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Checklist
 - [x] tested locally
 - [ ] added new dependencies
 - [x] updated the docs
 - [ ] added a test

-----
[View rendered doc/community-build/cloud/AWS/README.md](https://github.com/shailesh-vaidya/cortx/blob/terraform-scripts/doc/community-build/cloud/AWS/README.md)

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by shailesh-vaidya** [comment]
@johnbent @justinzw @hessio  Could you please review this PR.

**Review by hessio — APPROVED** [review]
Looks good.

**Review by johnbent — APPROVED** [review]
Excellent @shailesh-vaidya ! It does need one more thing however which is a link to it from some other existing page. Can you please ask @novium258 and @swatid and @mukul-seagate11 where a good page is to add a link to this one? We can actually merge this now but we need to remember to link it from some existing place. I'll merge it now and create that issue.

**Pull request merged**
