### PR TITLE
Fix Codacy "Quote this to prevent word splitting"

### PR DESCRIPTION
**Pull request by hessio**
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>

### Changes
 - Added double quotes to expression to allow expansions of expressions

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by mukul-seagate11** [comment]
@hessio, I hope the suggested changes are tested & validated?

**Comment by hessio** [comment]
oh no I haven't tested it yet.

**Review by mukul-seagate11 — APPROVED** [review]
looks good, but lets make a practice to validate the changes so that the code should not break

**Pull request merged**
