### PR TITLE
update broken link pointing to OVA installation readme

### PR DESCRIPTION
**Pull request by daniarherikurniawan**
### Describe your changes in brief
This PR fixes the broken links

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by johnbent** [comment]
@hessio , should we merge this one?

**Comment by mukul-seagate11** [comment]
@daniarherikurniawan, also I see you had not signed the cla agreement for contributing to CORTX as,

`2021-06-21T15:51:48.242Z INFO The contributors @daniarherikurniawan have not signed the CLA, adding error status to the pull request`

**Comment by hessio** [comment]
> [**@hessio**](https://github.com/hessio) , should we merge this one?

Please. I think there will be one merge error as I changed this in the Quick Start Guide but the rest is required.

**Comment by daniarherikurniawan** [comment]
@mukul-seagate11, got it. I am sending my CLA document to seagate.
@hessio , I will update this PR to be mergeable with the main branch.

**Comment by hessio** [comment]
Great thanks @daniarherikurniawan

**Review by johnbent — APPROVED** [review]

**Pull request merged**
