### PR TITLE
REPLACED TODO WITH CURL CODE 

### PR DESCRIPTION
**Pull request by shelar1423**
**Replaced TODO with curl commands**
All the TODO is replaced by actual code curl, helps reader understand better and get knowledge of the code 
#1457 

-----
[View rendered cortx-s3samplecode/curl/README.md](https://github.com/shelar1423/cortx/blob/patch-1/cortx-s3samplecode/curl/README.md)

### CODE REVIEW

**Comment by hessio** [comment]
Please follow our tested by formatting, here is an example for reference https://github.com/shelar1423/cortx/tree/patch-1/cortx-s3samplecode/python#tested-by

**Comment by shelar1423** [comment]
@hessio  made the changes to format of tested by

**Comment by johnbent** [comment]
Just adding a link to #1457 which this PR addresses.

**Comment by shelar1423** [comment]
@johnbent  done with the changes requested

**Review by johnbent — APPROVED** [review]
LGTM. Thanks @shelar1423 !

**Comment by johnbent** [comment]
■ #SODACODE-PR-Accepted

**Comment by shelar1423** [comment]
@johnbent  can you kindly label this under sodacode2022
And sodalow

**Comment by shelar1423** [comment]
@johnbent  glad to contribute, so u commented that this PR is accepted for sodacode but there ain't any labels showing on this PR so shall I consider it as accepted or the labels are must for scoring?

**Comment by hessio** [comment]
closes #1457

**Comment by johnbent** [comment]
> @johnbent glad to contribute, so u commented that this PR is accepted for sodacode but there ain't any labels showing on this PR so shall I consider it as accepted or the labels are must for scoring?

Thanks @hessio for adding the labels!

**Comment by johnbent** [comment]
@hessio , should we merge this?

**Pull request merged**
