### PR TITLE
CORTX-Flask-IPFS Integration

### PR DESCRIPTION
**Pull request by MatthewBarrettUCD**
Signed-off-by: MatthewBarrettUCD <matt.barrett10@gmail.com>

-----
[View rendered doc/integrations/CORTX-Flask-MediaViewer/README.md](https://github.com/MatthewBarrettUCD/cortx/blob/main/doc/integrations/CORTX-Flask-MediaViewer/README.md)

### CODE REVIEW

**Comment by novium258** [comment]
@mukul-seagate11 please merge this hackathon entry.

**Comment by novium258** [comment]
@mukul-seagate11 please merge this hackathon entry.

**Comment by mukul-seagate11** [comment]
@MatthewBarrettUCD, I see Codacy has failed due to hardcode secret key mentioned as per https://github.com/Seagate/cortx/issues/1598 so please fix the same in your local branch & then commit so that this PR can be merged

**Review by hessio — APPROVED** [review]
Looks good.

**Comment by hessio** [comment]
@mukul-seagate11 please merge PR

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Pull request merged**
