### PR TITLE
Raspberry Pi X Samba X CORTX

### PR DESCRIPTION
**Pull request by raydenshogun**
RPi NAS server that automatically syncs with CORTX storage

Signed-off-by: Reia Suzuki solacexsonata@gmail.com

-----
[View rendered doc/integrations/rpi-samba/README.md](https://github.com/raydenshogun/cortx/blob/main/doc/integrations/rpi-samba/README.md)

### CODE REVIEW

**Comment by kaplanlior** [comment]
Hi @raydenshogun 

Thanks for the PR as part of the CORTX Hackathon :+1: 

Notice your PR is missing a DCO ( https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md ) and can't be accepted to CORTX without it ( https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md#contribution-process ).

Please sign your commits so that the DCO test can pass. If you need help, don't hesitate reaching out to me.

**Comment by raydenshogun** [comment]
Signed-off-by: Reia Suzuki <solacexsonata@gmail.com>

**Comment by raydenshogun** [comment]
> Hi @raydenshogun
> 
> Thanks for the PR as part of the CORTX Hackathon 👍
> 
> Notice your PR is missing a DCO ( https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md ) and can't be accepted to CORTX without it ( https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md#contribution-process ).
> 
> Please sign your commits so that the DCO test can pass. If you need help, don't hesitate reaching out to me.

Hi Kaplan, the DCO document states "While creating a Pull Request via the GitHub UI, add Signed-off-by: "Name" <email address> in the PR comments section", but my addition of the signoff in the original post and the comment did not trigger the pipeline again. Any help? Sorry, new to do this.

**Comment by kaplanlior** [comment]
If you could add the sign-off part of the commits, that would be great.
See instructions at https://github.com/Seagate/cortx/pull/1145/checks?check_run_id=3223253905

@johnbent, AFAIK, the "sign off" requirement is for the commits, while the DCO document mentions it's also possible on the PR. As the bot ignore that, can we clarify the requirement ?

**Comment by johnbent** [comment]
Thanks for your participation in our hackathon and thanks for a great integration!  I'll be merging this soon.  Sorry for the delay.

**Review by johnbent — APPROVED** [review]

**Pull request merged**
