### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by korenlev**
small change to start with , worked for me, i offer to review docs/guides and fix issues
see also: https://github.com/Seagate/cortx/issues/401 (i might fix in next commit)
br
koren lev

### CODE REVIEW

**Comment by korenlev** [comment]
Signed-off-by: Koren Lev <korenlev@gmail.com>

**Comment by johnbent** [comment]
Wow Koren!  We very happily accept your extremely generous "offer to review docs/guides and fix issues"!  Thanks and welcome to CORTX Community!

**Review by johnbent — APPROVED** [review]

**Comment by johnbent** [comment]
By the way, ignore the CLA issue.

**Comment by korenlev** [comment]
tx john, i plan to review while going through deployment and testing , i will continue later this week

**Comment by korenlev** [comment]
tx john, i plan to contribute while going through deployment and testing , i will continue later this week, can this be merged ?

**Review by johnbent — APPROVED** [review]

**Comment by johnbent** [comment]
@korenlev , merged!  Thanks!

**Pull request merged**
