### PR TITLE
Created the git tagging for OVA

### PR DESCRIPTION
**Pull request by TechWriter-Mayur**
Created the git-tagging for CORTX file for cloning individual components and entire stack.

-----
[View rendered doc/Git-tagging-in-CORTX.md](https://github.com/TechWriter-Mayur/cortx/blob/main/doc/Git-tagging-in-CORTX.md)

### CODE REVIEW

**Review by mukul-seagate11 — CHANGES_REQUESTED** [review]
the git tag is related to OVA R2 so should be updated in https://github.com/Seagate/cortx/tree/239089afb76c520ecfe958ce40f7dc475dc846b4/doc/ova/2.0.0 and then will be linked in release page

**Review by mukul-seagate11 — COMMENTED** [review]
file should be updated stating that git tag, CORTX-OVA-2.0.0-264 is specific to OVA 2.0.0 release

**Review by shailesh-vaidya — COMMENTED** [review]
@TechWriter-Mayur @mukul-seagate11  - Not sure if we need a separate file for this. I feel we can simply have an additional line at https://github.com/Seagate/cortx/blob/main/doc/community-build/Generate-Cortx-Build-Stack.md#procedure 

e.g. You can use `CORTX-OVA-2.0.0-264` instead of `main` to clone the latest tested TAG.

**Comment by mukul-seagate11** [comment]
> @TechWriter-Mayur @mukul-seagate11 - Not sure if we need a separate file for this. I feel we can simply have an additional line at https://github.com/Seagate/cortx/blob/main/doc/community-build/Generate-Cortx-Build-Stack.md#procedure
> 
> e.g. You can use `CORTX-OVA-2.0.0-264` instead of `main` to clone the latest tested TAG.

@TechWriter-Mayur, make sense to add the tagging instructions in suggested doc where separate section can be added for tagging for individual components & CORTX stack

**Comment by mukul-seagate11** [comment]
@TechWriter-Mayur, lets update the below instructions in https://github.com/Seagate/cortx/blob/main/doc/community-build/Generate-Cortx-Build-Stack.md#procedure and leave the OVA tag part as,

From CORTX Stack:
 
```
$ cd /root && git clone https://github.com/Seagate/cortx --recursive --depth=1
$ docker run --rm -v /root/cortx:/cortx-workspace ghcr.io/seagate/cortx-build:centos-7.8.2003 make checkout BRANCH=CORTX-OVA-2.0.0-264
$ cd <component_repo>
```

**Pull request closed without merging**
