### PR TITLE
Added test comment

### PR DESCRIPTION
**Pull request by harrison-seow-seagate**
Signed-off-by: Harrison Seow <harrison.seow@seagate.com>

### Changes
 - [x] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

Confirmed steps in the guide by testing

### How Has This Been Tested? (Optional)
 - [x] Please describe in detail how you tested your changes.
 - [x] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

Tested on Windows 10 Desktop, running VMWare Workstation 16 Player.
More info on this [issue](https://github.com/Seagate/cortx/issues/864).

### Checklist
 - [x] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

### CODE REVIEW

**Review by shailesh-vaidya — APPROVED** [review]
Looks good. @harrison-seow-seagate  Thanks for validating the steps.

**Comment by mukul-seagate11** [comment]
duplicate of https://github.com/Seagate/cortx/pull/895

**Comment by shailesh-vaidya** [comment]
@mukul-seagate11  I guess this is not a duplicate of https://github.com/Seagate/cortx/pull/895 . https://github.com/Seagate/cortx/pull/895 is for `doc/CORTX_on_Open_Virtual_Appliance.rst` and this (https://github.com/Seagate/cortx/pull/894) is for `doc/Release_Build_Creation.rst`

**Comment by harrison-seow-seagate** [comment]
Hi @mukul-seagate11, this is not a duplicate.

**Comment by mukul-seagate11** [comment]
yes, I had re-opened the PR

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Pull request merged**
