### PR TITLE
Modzy AI Cortx S3 Filesystem Scanner

### PR DESCRIPTION
**Pull request by vilaksh01**
### Describe your changes in brief
Using Modzy AI and Cortx for harnessing massive amounts of Unbounded and Unstructured data for organizations.

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

-----
[View rendered doc/integrations/cortx-modzy-ai/README.md](https://github.com/vilaksh01/cortx/blob/modzy-s3/doc/integrations/cortx-modzy-ai/README.md)

### CODE REVIEW

**Comment by novium258** [comment]
@mukul-seagate11 please merge this hackathon entry.

**Comment by mukul-seagate11** [comment]
@vilaksh01, can you update your local branch?

**Comment by vilaksh01** [comment]
@mukul-seagate11 i have updated my local branch 👍

**Review by mukul-seagate11 — APPROVED** [review]
looks good, so merging the hackathon pull request based on exceptional approval for DCO from legal

**Pull request merged**
