### PR TITLE
Added image to components.md page

### PR DESCRIPTION
**Pull request by hessio**
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>

### Changes
 - Added image to Components.md page

-----
[View rendered doc/Components.md](https://github.com/hessio/cortx/blob/patch-17/doc/Components.md)

### CODE REVIEW

**Review by johnbent — APPROVED** [review]

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by mukul-seagate11** [comment]
@hessio, do update your branch which should be up-to-date with main branch,

image

**Comment by hessio** [comment]
I have tried to do this but I am not able to

**Comment by johnbent** [comment]
Duplicate

**Pull request closed without merging**
