### PR TITLE
Created Demonstration Directory

### PR DESCRIPTION
**Pull request by TechWriter-Mayur**
Created the Demonstration directory and added the required files.
Sign-off by: Mayur Gupta <mayur.gupta@seagate.com>

### CODE REVIEW

**Review by johnbent — CHANGES_REQUESTED** [review]
This is just a folder with a bunch of binary files in it.  I see that these are supporting the wiki.  You need to add a link to the wiki page from some existing documentation.  Our number one rule is to never create an 'orphan' document which is not linked from existing documentation.  Also, can you please remove the movie files and work with @novium258 to upload them into youtube?

**Comment by johnbent** [comment]
@TechWriter-Mayur , can you address the requests here please?

**Comment by TechWriter-Mayur** [comment]
I have removed the .mp4 files and PDF files are linked with Wiki pages. Also created requests for YouTube. Once the videos are available on YouTube I will link update the links in Wiki pages.

**Comment by johnbent** [comment]
Closing this.

**Pull request closed without merging**
