### PR TITLE
Add Image Files

### PR DESCRIPTION
**Pull request by VenkyOS**

### CODE REVIEW

**Comment by VenkyOS** [comment]
This is a test PR raised based on the ask of @mukul-seagate11,

**Comment by johnbent** [comment]
@mukul-seagate11 , can we close this?

**Comment by mukul-seagate11** [comment]
wasn't toxic enough

**Comment by mukul-seagate11** [comment]
anger

**Comment by mukul-seagate11** [comment]
toxic

**Comment by mukul-seagate11** [comment]
closing as its a dummy PR for testing

**Pull request closed without merging**
