### PR TITLE
Update add_label_to_repos.sh

### PR DESCRIPTION
**Pull request by justinzw**
Added new Triage labels for us to label issues appropiately.

Signed-off-by: Justin Woo <justin.woo@seagate.com>

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by justinzw** [comment]
Thanks! Can we merge this?

@johnbent @mukul-seagate11

**Review by johnbent — CHANGES_REQUESTED** [review]
It shouldn't be my name directly embedded in here. Please replace with $GH_USER

**Comment by justinzw** [comment]
Thanks John, I went ahead and updated it. I also updated an adjacent python file that had your name in it. 

When you run it do you just define these variables locally? I can test it with one the the private repos I own.

**Pull request merged**
