### PR TITLE
Update RNTemplate.rst

### PR DESCRIPTION
**Pull request by VenkyOS**
Signed-off-by: Venkataraman Padmanabhan <venkataraman.padmanabhan@seagate.com>

ok that last one wasnt toxic enough more anger hate grrr screw you bot!!! lol

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by VenkyOS** [comment]
This PR was created to test the sentiment bot.

**Comment by mukul-seagate11** [comment]
ok that last one wasnt toxic enough more anger hate grrr screw you bot!!! lol

**Comment by johnbent** [comment]
Looks like it isn’t working? Stupid frigging thing.

________________________________

**Comment by mukul-seagate11** [comment]
@test-dummy...you are toxic bot

**Comment by mukul-seagate11** [comment]
you stupid nonsense bot

**Comment by mukul-seagate11** [comment]
threat

**Comment by mukul-seagate11** [comment]
toxic burn

**Comment by mukul-seagate11** [comment]
I'm kinda sad

**Comment by mukul-seagate11** [comment]
@all-contributors add

**Pull request merged**
