### PR TITLE
Added the CORTX workspace count

### PR DESCRIPTION
**Pull request by venkuppu-chn**
Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

### CODE REVIEW

**Review by shailesh-vaidya — APPROVED** [review]

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Review by johnbent — APPROVED** [review]

**Comment by johnbent** [comment]
@venkuppu-chn , I can't merge this because there are conflicts in the pickle which can't be resolved using the GUI.  Can you please resolve the conflicts and fix this PR?  Sorry for the hassle.

**Comment by mukul-seagate11** [comment]
@venkuppu-chn, do resolve the conflicts

**Comment by mukul-seagate11** [comment]
@venkuppu-chn, do resolve the conflicts,

image

**Comment by venkuppu-chn** [comment]
I'm closing this PR as I've created new PR as mentioned below.
https://github.com/Seagate/cortx/pull/902

**Pull request closed without merging**
