### PR TITLE
Update hardware specification & tested by section

### PR DESCRIPTION
**Pull request by mukul-seagate11**
Update hardware specification & tested by section

-----
[View rendered doc/ProvisionReleaseBuild.md](https://github.com/Seagate/cortx/blob/mukul-seagate11-patch-8/doc/ProvisionReleaseBuild.md)

### CODE REVIEW

**Review by mukul-seagate11 — COMMENTED** [review]
.

**Review by mukul-seagate11 — COMMENTED** [review]
.

**Comment by mukul-seagate11** [comment]
duplicate of https://github.com/Seagate/cortx/pull/1049

**Review by hessio — COMMENTED** [review]
I am not sure it is necessary to remove the steps under "Cleanup temporary repos"

**Pull request closed without merging**
