### PR TITLE
Testing Codacy warnings -- DO NOT MERGE

### PR DESCRIPTION
**Pull request by johnbent**
Signed-off-by: John Bent <john.bent@seagate.com>

testing codacy

-----
[View rendered doc/codacy_check/README.md](https://github.com/Seagate/cortx/blob/johnbent-patch-2/doc/codacy_check/README.md)

### CODE REVIEW

**Comment by johnbent** [comment]
Why isn't codacy complaining about bug.c? When I compile it with -Wall and -Wextra, I get the following:

/t/bug$ g++ -Wextra -Wall bug.c
bug.c: In function ‘int main()’:
bug.c:8:16: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
     if (false) ;
                ^
bug.c:6:10: warning: unused variable ‘unused_variable’ [-Wunused-variable]
     bool unused_variable=false;

**Comment by johnbent** [comment]
@mukul-seagate11 , can you please look at this? It looks like Codacy isn't working very well for us. I committed a known bug and it didn't complain. Is it set up correctly?

**Comment by mukul-seagate11** [comment]
> This issue/pull request has been marked as `needs attention` as it has been left pending without new activity for 4 days. Tagging @mukul-seagate11 for appropriate assignment. Sorry for the delay & Thank you for contributing to CORTX. We will get back to you as soon as possible.

@johnbent, figured out that this is a problem on CPPCheck so opened a bug on their platform i.e. https://sourceforge.net/p/cppcheck/discussion/development/thread/b8555bd19c/ with help from Codacy team and as soon as this bug get fixed, it will start showing the issues as expected in Codacy.

**Comment by mukul-seagate11** [comment]
> @mukul-seagate11 , can you please look at this? It looks like Codacy isn't working very well for us. I committed a known bug and it didn't complain. Is it set up correctly?

@johnbent, figured out that this is a problem on CPPCheck so opened a bug on their platform i.e. https://sourceforge.net/p/cppcheck/discussion/development/thread/b8555bd19c/ with help from Codacy team and as soon as this bug get fixed, it will start showing the issues as expected in Codacy.

**Comment by johnbent** [comment]
Closing this as there are other efforts underway to improve our collective usage of Codacy.

**Pull request closed without merging**
