### PR TITLE
modified Update Git to the latest version section

### PR DESCRIPTION
**Pull request by yanqingfu**
Signed-off-by: Yanqing Fu yanqing.f.fu@seagate.com

### CODE REVIEW

**Review by johnbent — APPROVED** [review]

**Comment by johnbent** [comment]
@mukul-seagate11 , can you please review?

**Comment by huanghua78** [comment]
I don't know the reason why we need to update git to latest version.
Maybe we need to clarify this? In this document?

Why are we required to install something from `https://packages.endpoint.com/`  ?
Is this a trusted source?

**Comment by yanqingfu** [comment]
@huanghua78 

logic is here: 

 https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md

image

https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#10-Prerequisites

image

the original text is like this, I just reorganize it 

image

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Pull request merged**
