### PR TITLE
add cortx laravel doc

### PR DESCRIPTION
**Pull request by shusiner**
### Describe your changes in brief
Integrate Cortx with Laravel Rest API

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Checklist
 - [ ] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

-----
[View rendered doc/integrations/cortx_laravel.md](https://github.com/shusiner/cortx/blob/main/doc/integrations/cortx_laravel.md)

### CODE REVIEW

**Comment by kaplanlior** [comment]
Hi @shusiner 

Thanks for the PR as part of the CORTX Hackathon :+1: 

Notice your PR is missing a DCO ( https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md ) and can't be accepted to CORTX without it ( https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md#contribution-process ).

Please sign your commits so that the DCO test can pass. If you need help, don't hesitate reaching out to me.

**Comment by shusiner** [comment]
Hi @kaplanlior, I think I have already signed as shown above. Can I check if I have done the steps correctly?
image

**Comment by kaplanlior** [comment]
> Hi @kaplanlior, I think I have already signed as shown above. Can I check if I have done the steps correctly?

Two out of three commits are signed. You need to also sign the reminding one to make the DCO bot happy.
You can find some useful commands [here](https://github.com/Seagate/cortx/pull/1147/checks?check_run_id=3225458247).

**Comment by johnbent** [comment]
Thanks for your participation in our hackathon and thanks for a great integration!  I'll be merging this soon.  Sorry for the delay.

**Review by johnbent — APPROVED** [review]

**Pull request merged**
