### PR TITLE
Update local test of OVA 1.0.4

### PR DESCRIPTION
**Pull request by nrady**
### Describe your changes in brief
Update test result of OVA 1.0.4 on Windows 10 with VMWare Workstation 16 Pro
### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Screenshots (if appropriate)
image

### Checklist
 - [ /] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
@nrady, looks good, also can you "signoff" your commits to pass DCO

**Review by nrady — COMMENTED** [review]
Thanks for review.

**Comment by nrady** [comment]
Signed-off-by: Amnuay Boottrokat<amnuay.boottrakoat@seagate.com>

**Comment by nrady** [comment]
> @nrady, looks good, also can you "signoff" your commits to pass DCO

My bad to click around as this is my first time commit. Please you guideline me how to success this commit. Thanks

**Pull request merged**
