### PR TITLE
[CORTX Hackathon Integration] Goofys/CORTX 

### PR DESCRIPTION
**Pull request by c-l-j-y**
Pull request for our integration, Goofys/CORTX, for Seagate CORTX Hackathon Singapore - by Team Zelda

-----
[View rendered doc/integrations/goofys/README.md](https://github.com/c-l-j-y/cortx/blob/main/doc/integrations/goofys/README.md)

### CODE REVIEW

**Comment by kaplanlior** [comment]
Hi @c-l-j-y 

Thanks for the PR as part of the CORTX Hackathon :+1: 

Notice your PR is missing a DCO ( https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md ) and can't be accepted to CORTX without it ( https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md#contribution-process ).

Please sign your commits so that the DCO test can pass. If you need help, don't hesitate reaching out to me.

**Comment by johnbent** [comment]
Oh shoot.  I want to merge this but these conflicts should be removed:

`cortx-hare`

`cortx-manager`

`cortx-motr`

`cortx-prvsnr`

`cortx-s3server`

`cortx-utils`

`metrics/pickles/activity_hashes.EMCECS.pickle`

`metrics/pickles/activity_hashes.daos-stack.pickle`

`metrics/pickles/activity_hashes.open-io.pickle`

`metrics/pickles/activity_hashes.openstack.pickle`

`metrics/pickles/activity_hashes.pickle`

`metrics/pickles/author_activity.EMCECS.pickle`

`metrics/pickles/author_activity.daos-stack.pickle`

`metrics/pickles/author_activity.open-io.pickle`

`metrics/pickles/author_activity.openstack.pickle`

`metrics/pickles/author_activity.pickle`

`metrics/pickles/compare_projects.pickle`

`metrics/pickles/cortx_community.Ceph.pickle`

`metrics/pickles/cortx_community.EMCECS.pickle`

`metrics/pickles/cortx_community.MinIO.pickle`

`metrics/pickles/cortx_community.daos-stack.pickle`

`metrics/pickles/cortx_community.open-io.pickle`

`metrics/pickles/cortx_community.openstack.pickle`

`metrics/pickles/cortx_community.pickle`

`metrics/pickles/persistent_stats.Ceph.pickle`

None of these files should be modified in this PR.  @mukul-seagate11 , do you know how to clean this up?

**Comment by kaplanlior** [comment]
@c-l-j-y , Let try to solve this, so the CORTX team could merge your PR.
```
git remote add upstream git@github.com:Seagate/cortx.git
git fetch upstream
git rebase upstream/main
```

To verify the diff is only what we want for the PR:
```
$ git diff --stat upstream/main
 doc/images/goofys.jpg                         | Bin 0 -> 27746 bytes
 doc/integrations/README.rst                   |   6 +++++-
 doc/integrations/goofys/README.md             |  38 ++++++++++++++++++++++++++++++++++++++
 doc/integrations/goofys/goofys-cortx-setup.sh |  25 +++++++++++++++++++++++++
 doc/integrations/goofys/video-thumbnail.png   | Bin 0 -> 770861 bytes
 5 files changed, 68 insertions(+), 1 deletion(-)
```


Then you'll have to push (probably with --force) to your branch on github again,
and that would update this PR.

**Comment by c-l-j-y** [comment]
Sorry I don't really know how to fix this so I think the quickest solution is to simply start another pull request. I will be closing this for now.

**Comment by johnbent** [comment]
Thank you @c-l-j-y , you saved me a lot of work as I also had no idea how to fix this!  :)

**Pull request closed without merging**
