### PR TITLE
Splunk Integration Document

### PR DESCRIPTION
**Pull request by justinzw**
Here is a document that describes how to integrate CORTX with Splunk.

The main file is in `splunk.md` with corresponding images in a sub-folder `splunk`

I've also created a folder `integrations` where we can list the integrations there.

### CODE REVIEW

**Comment by justinzw** [comment]
Looks like I have to update my DCO since DCO failed.

**Comment by mukul-seagate11** [comment]
> Looks like I have to update my DCO since DCO failed.

DCO is passed now

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Review by gregnsk — CHANGES_REQUESTED** [review]
- Getting the right IP by running 'ip a l` - this is ok for CORTX / open source / Linux geeks, but it's not the easiest nor natural way for storage admins.
	Please refer to the URL as reported when you create an S3 account

- replace "*Step 2: Installing the integration:*" with "Step 2: Configure Splunk"
Also, add a note: These steps apply to a single-indexer configuration. See Splunk documentation for more details about clustered indexers setup

 

English: "is information on how to configuring a remote"

 

"Step 3 Restart your Splunk server" - I think it should be part of Step 2. You're just applying the configuration

 

Validating Splunk with CORTX is the actual step 3

 

English: "verify that there is activity being uploaded"

**Comment by justinzw** [comment]
Thanks @gregnsk  I made the suggested changes.

**Pull request merged**
