### PR TITLE
Added link to Wiki on how to build Motr in cluster

### PR DESCRIPTION
**Pull request by hessio**
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>

### Changes
 - Changed TODO to link for building Motr from source and running it in a cluster of nodes

### How Has This Been Tested? (Optional)
 - Tested using VMware Workstation Pro 16 on Windows laptop using iso CentOS 7.8.2003

-----
[View rendered QUICK_START.md](https://github.com/Seagate/cortx/blob/hessio-patch-2/QUICK_START.md)

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Review by johnbent — APPROVED** [review]
Thanks Patrick.  Approving this and merging it.  But shouldn't it say 'DONE?' instead of LINK?  I think we want 'DONE?' until we have 2 successful folks in the 'Tested By' section.

**Comment by johnbent** [comment]
@mukul-seagate11 , can we please get Patrick added to CLA if he isn't yet?

**Comment by johnbent** [comment]
@mukul-seagate11 , actually is there a way to get an @seagate.com wildcard added to the CLA?

**Comment by mukul-seagate11** [comment]
@johnbent, let me check the feasibility to get @seagate.com wildcard added to CLA

**Pull request merged**
