### PR TITLE
codacy improvement

### PR DESCRIPTION
**Pull request by yanqingfu**
https://github.com/Seagate/cortx/issues/1526

use heading to introduce a section and also change the sequence in the proper order

Signed-off-by: Yanqing Fu <yanqing.f.fu@seagate.com>

-----
[View rendered doc/integrations/dvc/README.md](https://github.com/yanqingfu/cortx/blob/patch-3/doc/integrations/dvc/README.md)

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by mukul-seagate11** [comment]
@yanqingfu, can you update your branch

**Comment by yanqingfu** [comment]
> @yanqingfu, can you update your branch

DCO?

**Comment by mukul-seagate11** [comment]
@yanqingfu, can you update your local branch

**Review by mukul-seagate11 — CHANGES_REQUESTED** [review]
can you update your local branch and do sign-off your commits via DCO

**Comment by yanqingfu** [comment]
> can you update your local branch and do sign-off your commits via DCO

done

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Pull request merged**
