### PR TITLE
EOS-26653: Added submodule for K8s and RE repository

### PR DESCRIPTION
**Pull request by venkuppu-chn**
Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>

### Describe your changes in brief
Adding the submodule workflow 

### Changes
 - [ ] Why is this change required? What problem does it solve?
 - [ ] If proposing a new change then please raise an issue first

### How Has This Been Tested? (Optional)
 - [ ] Please describe in detail how you tested your changes.
 - [ ] Include details of your testing environment, and the tests you ran to
 - [ ] How your change affects other areas of the code, etc.

### Checklist
 - [x] tested locally
 - [ ] added new dependencies
 - [ ] updated the docs
 - [ ] added a test

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by shailesh-vaidya** [comment]
@venkuppu-chn  - Please validate that the below command works without any issues after the addition of submodules. 

`docker run --rm -v /root/cortx:/cortx-workspace ghcr.io/seagate/cortx-build:centos-7.9.2009 make checkout BRANCH=kubernetes`

This command is used in - https://github.com/Seagate/cortx/tree/main/doc/community-build/docker/cortx-all

**Comment by venkuppu-chn** [comment]
> @venkuppu-chn - Please validate that the below command works without any issues after the addition of submodules.
> 
> `docker run --rm -v /root/cortx:/cortx-workspace ghcr.io/seagate/cortx-build:centos-7.9.2009 make checkout BRANCH=kubernetes`
> 
> This command is used in - https://github.com/Seagate/cortx/tree/main/doc/community-build/docker/cortx-all

image

Yes, the command is not working as anticipated.

**Comment by venkuppu-chn** [comment]
> @venkuppu-chn - Please validate that the below command works without any issues after the addition of submodules.
> 
> `docker run --rm -v /root/cortx:/cortx-workspace ghcr.io/seagate/cortx-build:centos-7.9.2009 make checkout BRANCH=kubernetes`
> 
> This command is used in - https://github.com/Seagate/cortx/tree/main/doc/community-build/docker/cortx-all

image

As you mentioned in call it is failed while checkout the kubernetes branch, we have to exclude the cortx-k8s repo while checkout kubernetes.

**Comment by venkuppu-chn** [comment]
> @venkuppu-chn - Please validate that the below command works without any issues after the addition of submodules.
> 
> `docker run --rm -v /root/cortx:/cortx-workspace ghcr.io/seagate/cortx-build:centos-7.9.2009 make checkout BRANCH=kubernetes`
> 
> This command is used in - https://github.com/Seagate/cortx/tree/main/doc/community-build/docker/cortx-all

After adding the cortx-k8 in Makefile, I'm able to checkout the kubernates branch. 
[full_log.log](https://github.com/Seagate/cortx/files/7773490/full_log.log)

**Review by shailesh-vaidya — APPROVED** [review]
Validated with the latest image that checkout is working with the addition of new submodules. 

```
[root@ssc-vm-3256 ~]# docker run --rm -v /root/cortx:/cortx-workspace ghcr.io/seagate/cortx-re/cortx-build-internal:centos-7.9.2009  make checkout BRANCH=kubernetes
*************** checkout code *********************
pushd cortx-workspace && \
        for component in $(ls -1d cortx-* | grep -Evx 'cortx-k8s||cortx-experiments||cortx-posix||cortx-multisite||cortx-s3samplecode'); do pushd $component; git clean -fdx; git checkout .; git pull -p --all; git checkout $BRANCH || exit 1; popd ; done  && \
popd || (echo "ERROR: Failed to checkout specified branch/tag Exiting..."; exit 1)
/cortx-workspace /
/cortx-workspace/cortx-ha /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'kubernetes'
Your branch is up-to-date with 'origin/kubernetes'.
/cortx-workspace /
/cortx-workspace/cortx-hare /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'kubernetes'
Your branch is up-to-date with 'origin/kubernetes'.
/cortx-workspace /
/cortx-workspace/cortx-management-portal /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'kubernetes'
Your branch is up-to-date with 'origin/kubernetes'.
/cortx-workspace /
/cortx-workspace/cortx-manager /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'kubernetes'
Your branch is up-to-date with 'origin/kubernetes'.
/cortx-workspace /
/cortx-workspace/cortx-monitor /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'kubernetes'
Your branch is up-to-date with 'origin/kubernetes'.
/cortx-workspace /
/cortx-workspace/cortx-motr /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'kubernetes'
Your branch is up-to-date with 'origin/kubernetes'.
/cortx-workspace /
/cortx-workspace/cortx-prvsnr /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'kubernetes'
Your branch is up-to-date with 'origin/kubernetes'.
/cortx-workspace /
/cortx-workspace/cortx-s3server /cortx-workspace /
Fetching origin
From https://github.com/Seagate/cortx-s3server
   a5101ae0..9af391ac  object-versioning -> origin/object-versioning
Already up-to-date.
Already on 'kubernetes'
M       third_party/motr
Your branch is up-to-date with 'origin/kubernetes'.
/cortx-workspace /
/cortx-workspace/cortx-utils /cortx-workspace /
Fetching origin
From https://github.com/Seagate/cortx-utils
   e430cbf..591cb1f  EOS-26948  -> origin/EOS-26948
Already up-to-date.
Already on 'kubernetes'
Your branch is up-to-date with 'origin/kubernetes'.
/cortx-workspace /
/
[root@ssc-vm-3256 ~]#
```

**Pull request merged**
